<template>
  <div>
    <Header />
    <div class="container has-text-white py-6 mobile-padding">
      <h3 class="is-size-3 mt-6 mb-2">
        Introduction
      </h3>
      <p>With the following privacy policy, we would like to inform you about the types of your personal data (hereinafter also referred to as "data" for short) that we process, for what purposes and to what extent. The privacy policy applies to all processing of personal data carried out by us, both in the context of the provision of our services and in particular on our websites, in mobile applications and within external online presences, such as our social media profiles (hereinafter collectively referred to as "Online Offerings").</p>
      <p>The terms used are not gender-specific.</p>
      <p>As of July 8, 2021</p>
      <h3 class="is-size-3 mt-6 mb-2">
        Table of Contents
      </h3>
      <ul class="index pl-4 mb-4">
        <li><a class="index-link" href="#m14">Introduction</a></li><li><a class="index-link" href="#m3">Person responsible</a></li><li><a class="index-link" href="#mOverview">Overview of processing</a></li><li><a class="index- link" href="#m13">Relevant legal basis</a></li><li><a class="index-link" href="#m27">Security measures</a></li><li><a class="index-link" href="#m12">Deletion of data</a></li><li><a class="index- link" href="#m134">Use of cookies</a></li><li><a class="index-link" href="#m225">Provision of the online offer and web hosting</a></li><li><a class="index- link" href="#m15">Change and update privacy policy</a></li><li><a class="index-link" href="#m10">Rights of data subjects</a></li><li><a class="index-link" href="#m42">Definitions of terms</a></li>
      </ul>
      <h3 id="m3" class="is-size-3 mt-6 mb-2">
        Responsible
      </h3>
      <p>Sarah Maria Leidisch<br>Heßheimer Straße 8<br>67227 Frankenthal</p>
      <p>Email address: <a href="mailto:shivelle@gmx.net">shivelle@gmx.net</a>.</p>
      <p>Imprint: <a href="https://sleidisch.com/de/impressum" target="_blank">https://sleidisch.com/de/impressum</a>.</p>
      <h3 id="mOverview" class="is-size-3 mt-6 mb-2">
        Processing overview
      </h3>
      <p>The following overview summarizes the types of data processed and the purposes of their processing, and refers to the data subjects.</p><h3>Types of data processed</h3>
      <ul class="index pl-4 mb-4">
        <li>Content data (e.g. input in online forms).</li><li>Contact data (e.g. e-mail, phone numbers).</li><li>Meta/communication data (e.g. device information, IP addresses).</li><li>Use data (e.g. websites visited, interest in content, access times).</li>
      </ul><h3>Categories of data subjects</h3>
      <ul class="index pl-4 mb-4">
        <li>Communication partners.</li><li>Users (e.g., website visitors, users of online services).</li>
      </ul><h3>Purposes of processing</h3>
      <ul class="index pl-4 mb-4">
        <li>Providing our online services and user experience</li><li>Direct marketing (e.g. by email or postal mail)</li><li>Contact requests and communication.</li>
      </ul>
      <h3 id="m13" class="is-size-3 mt-6 mb-2">
        Relevant legal basis
      </h3><p>The following is an overview of the legal bases of the GDPR on the basis of which we process personal data. Please note that in addition to the provisions of the GDPR, national data protection regulations may apply in your or our country of residence or domicile. Furthermore, should more specific legal bases be relevant in individual cases, we will inform you of these in the privacy policy.</p>
      <ul class="index pl-4 mb-4">
        <li><strong class="has-text-white has-text-weight-bold">Consent (Art. 6 para. 1 p. 1 lit. a. DSGVO)</strong> - The data subject has given consent to the processing of personal data concerning him or her for a specific purpose or purposes.</li><li><strong class="has-text-white has-text-weight-bold">Registered interests (Art. 6 para. 1 p. 1 lit. f. DSGVO)</strong> - Processing is necessary to protect the legitimate interests of the controller or a third party, unless such interests are overridden by the interests or fundamental rights and freedoms of the data subject which require the protection of personal data.</li>
      </ul><p><strong class="has-text-white has-text-weight-bold">National data protection regulations in Germany</strong>: In addition to the data protection regulations of the General Data Protection Regulation, national regulations on data protection apply in Germany. These include, in particular, the Act on Protection against Misuse of Personal Data in Data Processing (Federal Data Protection Act - BDSG). In particular, the BDSG contains special regulations on the right to information, the right to erasure, the right to object, the processing of special categories of personal data, processing for other purposes and transmission, as well as automated decision-making in individual cases, including profiling. Furthermore, it regulates data processing for employment purposes (Section 26 BDSG), in particular with regard to the establishment, implementation or termination of employment relationships as well as the consent of employees. Furthermore, state data protection laws of the individual federal states may apply.</p>
      <h3 id="m27" class="is-size-3 mt-6 mb-2">
        Security Measures
      </h3><p>We take appropriate technical and organizational measures in accordance with the law, taking into account the state of the art, the costs of implementation and the nature, scope, circumstances and purposes of the processing, as well as the different probabilities of occurrence and the level of risk to the rights and freedoms of natural persons, in order to ensure a level of protection appropriate to the risk.</p>
      <p>Measures include, in particular, ensuring the confidentiality, integrity, and availability of data by controlling physical and electronic access to data as well as access to, entry into, disclosure of, assurance of availability of, and segregation of data concerning them. Furthermore, we have established procedures to ensure the exercise of data subjects' rights, the deletion of data, and responses to data compromise. Furthermore, we already take the protection of personal data into account during the development or selection of hardware, software as well as procedures in accordance with the principle of data protection, through technology design and through data protection-friendly default settings.</p>
      <p><strong class="has-text-white has-text-weight-bold">SSL encryption (https)</strong>: To protect your data transmitted via our online offer, we use SSL encryption. You can recognize such encrypted connections by the prefix https:// in the address bar of your browser.</p>
      <h3 id="m12" class="is-size-3 mt-6 mb-2">
        Data deletion
      </h3><p>The data we process will be deleted in accordance with legal requirements as soon as their consents permitted for processing are revoked or other permissions cease to apply (e.g. if the purpose of processing this data has ceased to apply or it is no longer necessary for the purpose).</p>
      <p>If the data are not deleted because they are required for other and legally permissible purposes, their processing will be limited to these purposes. That is, the data will be blocked and not processed for other purposes. This applies, for example, to data that must be retained for reasons of commercial or tax law or whose storage is necessary for the assertion, exercise or defense of legal claims or for the protection of the rights of another natural person or legal entity.</p>
      <p>Our privacy notices may also include further information on the retention and deletion of data that takes precedence for the processing operations in question.</p>
      <h3 id="m134" class="is-size-3 mt-6 mb-2">
        Use of cookies
      </h3><p>Cookies are text files that contain data from websites or domains visited and are stored by a browser on the user's computer. The primary purpose of a cookie is to store information about a user during or after their visit within an online site. Stored information may include, for example, language settings on a website, login status, a shopping cart, or where a video was watched. We further include in the term cookies other technologies that perform the same functions as cookies (e.g., when user details are stored using pseudonymous online identifiers, also referred to as "user IDs").</p>
      <p><strong class="has-text-white has-text-weight-bold">The following cookie types and functions are distinguished:</strong></p>
      <ul class="index pl-4 mb-4">
        <li><strong class="has-text-white has-text-weight-bold">Temporary cookies (also: session cookies):</strong>&nbsp;Temporary cookies are deleted at the latest after a user has left an online offer and closed his browser.</li><li><strong class="has-text-white has-text-weight-bold">Permanent cookies:</strong>&nbsp;Permanent cookies remain stored even after closing the browser. For example, the login status can be saved or preferred content can be displayed directly when the user revisits a website. Likewise, the interests of users used for reach measurement or marketing purposes can be stored in such a cookie.</li><li><strong class="has-text-white has-text-weight-bold">First-party cookies:</strong>&nbsp;First-party cookies are set by ourselves. </li><li><strong class="has-text-white has-text-weight-bold">Third-party cookies (also: third-party cookies)</strong>: Third-party cookies are mainly used by advertisers (so-called third parties) to process user information. </li><li><strong class="has-text-white has-text-weight-bold">Necessary (also: essential or absolutely necessary) cookies:</strong> Cookies may, on the one hand, be absolutely necessary for the operation of a website (e.g. to store logins or other user inputs or for security reasons). </li><li><strong class="has-text-white has-text-weight-bold">Statistics, marketing and personalization cookies</strong>: Furthermore, cookies are usually also used in the context of range measurement and when the interests of a user or his behavior (e.g. viewing certain content, use of functions, etc.) on individual web pages are stored in a user profile. Such profiles are used, for example, to show users content that matches their potential interests. This process is also referred to as "tracking", i.e., tracking the potential interests of users. Insofar as we use cookies or "tracking" technologies, we inform you separately in our privacy policy or in the context of obtaining consent.</li>
      </ul><p><strong class="has-text-white has-text-weight-bold">Notes on legal bases: </strong>On which legal basis we process your personal data using cookies depends on whether we ask you for consent. If this is the case and you consent to the use of cookies, the legal basis for the processing of your data is the declared consent. Otherwise, the data processed with the help of cookies is processed on the basis of our legitimate interests (e.g. in a business operation of our online offer and its improvement) or, if the use of cookies is necessary to fulfill our contractual obligations.</p>
      <p><strong class="has-text-white has-text-weight-bold">Storage period: </strong>If we do not provide you with explicit information about the storage period of permanent cookies (e.g. in the context of a so-called cookie opt-in), please assume that the storage period can be up to two years.</p>
      <p><strong class="has-text-white has-text-weight-bold">General information on revocation and objection (opt-out): </strong> Depending on whether the processing is based on consent or legal permission, you have the option at any time to revoke any consent given or to object to the processing of your data by cookie technologies (collectively referred to as "opt-out"). You can initially declare your objection by means of your browser settings, e.g. by deactivating the use of cookies (whereby this may also restrict the functionality of our online offer). An objection to the use of cookies for online marketing purposes can also be declared by means of a variety of services, especially in the case of tracking, via the websites <a href="https://optout.aboutads.info" target="_blank">https://optout.aboutads.info</a> and <a href="https://www.youronlinechoices.com/" target="_blank">https://www.youronlinechoices.com/</a>. In addition, you can receive further instructions on how to object in the context of the information on the service providers and cookies used.</p>
      <p><strong class="has-text-white has-text-weight-bold">Processing of cookie data on the basis of consent</strong>: We use a cookie consent management procedure, in the context of which the consent of users to the use of cookies, or the processing and providers mentioned in the cookie consent management procedure can be obtained and managed and revoked by users. Here, the declaration of consent is stored in order not to have to repeat its query and to be able to prove the consent in accordance with the legal obligation. The storage can take place on the server side and/or in a cookie (so-called opt-in cookie, or with the help of comparable technologies), in order to be able to assign the consent to a user or their device. Subject to individual information on the providers of cookie management services, the following information applies: The duration of the storage of consent can be up to two years. Here, a pseudonymous user identifier is formed and stored with the time of consent, information on the scope of consent (e.g., which categories of cookies and/or service providers) as well as the browser, system and end device used.</p>
      <ul class="m-elements">
        <li><strong class="has-text-white has-text-weight-bold">Types of data processed:</strong> Usage data (e.g. websites visited, interest in content, access times), meta/communication data (e.g. device information, IP addresses).</li><li><strong class="has-text-white has-text-weight-bold">Person(s) concerned:</strong> Users (e.g.. E.g. website visitors, users of online services).</li><li><strong class="has-text-white has-text-weight-bold">Legal basis:</strong> Consent (Art. 6 para. 1 p. 1 lit. a. DSGVO), Legitimate Interests (Art. 6 para. 1 p. 1 lit. f. DSGVO).</li>
      </ul>
      <h3 id="m225" class="is-size-3 mt-6 mb-2">
        Provision of the online offer and web hosting
      </h3><p>In order to provide our Online Offer securely and efficiently, we use the services of one or more web hosting providers from whose servers (or servers managed by them) the Online Offer can be accessed. For these purposes, we may use infrastructure and platform services, computing capacity, storage space and database services as well as security services and technical maintenance services.</p>
      <p>The data processed in the course of providing the hosting service may include all information relating to the users of our online service, which is generated in the course of use and communication. This regularly includes the IP address, which is necessary to be able to deliver the contents of online offers to browsers, and all entries made within our online offer or from websites.</p>
      <p><strong class="has-text-white has-text-weight-bold">Collection of access data and log files</strong>: We ourselves (or our web hosting provider) collect data on each access to the server (so-called server log files). The server log files may include the address and name of the web pages and files accessed, date and time of access, data volumes transferred, notification of successful access, browser type and version, the user's operating system, referrer URL (the previously visited page) and, as a rule, IP addresses and the requesting provider.</p>
      <p>The server log files can be used on the one hand for security purposes, e.g. to avoid overloading the servers (especially in the case of abusive attacks, so-called DDoS attacks), and on the other hand to ensure the utilization of the servers and their stability.</p>
      <ul class="m-elements">
        <li><strong class="has-text-white has-text-weight-bold">Types of data processed:</strong> Content data (e.g. input in online forms), usage data (e.g. websites visited, interest in content, access times), meta/communication data (e.g. device information, IP addresses).</li><li><strong class="has-text-white has-text-weight-bold">People concerned:</strong> Users (e.g.. E.g. website visitors, users of online services).</li><li><strong class="has-text-white has-text-weight-bold">Purposes of processing:</strong> Provision of our online offer and user-friendliness.</li><li><strong class="has-text-white has-text-weight-bold">Legal basis:</strong> Legitimate interests (Art. 6 para. 1 p. 1 lit. f. DSGVO).</li>
      </ul>
      <h3 id="m15" class="is-size-3 mt-6 mb-2">
        Amendment and update of the privacy policy
      </h3>
      <p>We encourage you to periodically review the contents of our Privacy Policy. We adapt the Privacy Policy as soon as the changes in the data processing activities we carry out make it necessary. We will inform you as soon as the changes require an act of cooperation on your part (e.g. consent) or other individual notification.</p>
      <p>Where we provide addresses and contact information for companies and organizations in this Privacy Policy, please note that addresses may change over time and please check the information before contacting us.</p>
      <h3 id="m10" class="is-size-3 mt-6 mb-2">
        Rights of data subjects
      </h3><p>As a data subject, you are entitled to various rights under the GDPR, which arise in particular from Art. 15 to 21 GDPR:</p>
      <ul class="index pl-4 mb-4">
        <li><strong class="has-text-white has-text-weight-bold">Right of objection: you have the right to object at any time, on grounds relating to your particular situation, to the processing of personal data concerning you which is carried out on the basis of Article 6(1)(e) or (f) of the DSGVO; this also applies to profiling based on these provisions. If the personal data concerning you is processed for the purpose of direct marketing, you have the right to object at any time to the processing of personal data concerning you for the purpose of such marketing; this also applies to profiling, insofar as it is related to such direct marketing.</strong></li><li><strong class="has-text-white has-text-weight-bold">Right of withdrawal of consent:</strong> You have the right to withdraw consent given at any time. </li><li><strong class="has-text-white has-text-weight-bold">Right of access:</strong> You have the right to request confirmation as to whether data in question is being processed and to information about this data, as well as further information and copy of the data in accordance with legal requirements. </li><li><strong class="has-text-white has-text-weight-bold">Right to rectification:</strong> You have the right, in accordance with the law, to request that the data concerning you be completed or that inaccurate data concerning you be rectified. </li><li><strong class="has-text-white has-text-weight-bold">Right to erasure and restriction of processing:</strong> You have, in accordance with the law, the right to request that data concerning you be erased without undue delay, or alternatively, in accordance with the law, to request restriction of the processing of the data. </li><li><strong class="has-text-white has-text-weight-bold">Right to data portability:</strong> You have the right to receive data concerning you, which you have provided to us, in a structured, common and machine-readable format in accordance with the legal requirements, or to demand its transfer to another responsible party. </li><li><strong class="has-text-white has-text-weight-bold">Complaint to supervisory authority:</strong> Without prejudice to any other administrative or judicial remedy, you have the right to lodge a complaint with a supervisory authority, in particular in the Member State of your habitual residence, place of work or place of the alleged infringement, if you consider that the processing of personal data concerning you infringes the provisions of the GDPR.</li>
      </ul>
      <h3 id="m42" class="is-size-3 mt-6 mb-2">
        Definitions
      </h3>
      <p>This section provides an overview of the terms used in this privacy statement. Many of the terms are taken from the law and defined primarily in Article 4 of the GDPR. The legal definitions are binding. The following explanations, on the other hand, are primarily intended to aid understanding. The terms are sorted alphabetically.</p>
      <ul class="glossary">
        <li><strong class="has-text-white has-text-weight-bold">Personal data:</strong> "Personal data" means any information relating to an identified or identifiable natural person (hereinafter "data subject"); an identifiable natural person is one who can be identified, directly or indirectly, in particular by reference to an identifier such as a name, an identification number, location data, an online identifier (eg. e.g. cookie) or to one or more special characteristics that are an expression of the physical, physiological, genetic, mental, economic, cultural or social identity of that natural person. </li><li><strong class="has-text-white has-text-weight-bold">Controller:</strong> The "controller" is the natural or legal person, public authority, agency or other body which alone or jointly with others determines the purposes and means of the processing of personal data. </li><li><strong class="has-text-white has-text-weight-bold">processing:</strong> "Processing" means any operation or set of operations which is performed upon personal data, whether or not by automatic means. The term is broad and includes virtually any handling of data, whether collecting, evaluating, storing, transmitting or deleting. </li>
      </ul>
    </div>
  </div>
</template>

<script>
export default {
  nuxtI18n: {
    paths: {
      de: '/datenschutz',
      en: '/data-protection'
    }
  }
}
</script>
